package com.zuct.db.zuct_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CoursesBaseDto PLEASE EDIT ../CoursesDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Courses object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.zuct.db.zuct_db.entity.Courses;
// Import relations
import com.zuct.db.zuct_db.dtos.infos.ProgramsInfo;


import com.zuct.db.zuct_db.dtos.infos.LecturersInfo;


import com.zuct.db.zuct_db.dtos.infos.StudentsInfo;



public class CoursesBaseDto {
	
	private Long _id;
	
	// Attributes
    private String course_code;
    private String course_name;
	
	// Relations _contains
	private Long _contains;
	
	// Relations _teaches
	private Long _teaches;
	
	private List<StudentsInfo> studentss = new ArrayList<>();
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getCourse_code() {
		return course_code;
	}

	public void setCourse_code(String course_code) {
		this.course_code = course_code;
	}
	public String getCourse_name() {
		return course_name;
	}

	public void setCourse_name(String course_name) {
		this.course_name = course_name;
	}
    
	public void set_contains(ProgramsInfo _contains) {
		this._contains = _contains.get_id();
	}

	public Long get_contains() {
		return _contains;
	}
	
	public void set_teaches(LecturersInfo _teaches) {
		this._teaches = _teaches.get_id();
	}

	public Long get_teaches() {
		return _teaches;
	}
	

    
	// Relations students

	public List<StudentsInfo> get_takess() {
		return this.studentss;
	}

	public void set_takess(List<StudentsInfo> list) {
		this.studentss = list;
	}
	
}