package com.zuct.db.zuct_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ProgramsBaseDto PLEASE EDIT ../ProgramsDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Programs object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.zuct.db.zuct_db.entity.Programs;
// Import relations
import com.zuct.db.zuct_db.dtos.infos.LecturersInfo;

import com.zuct.db.zuct_db.dtos.infos.CoursesInfo;

import com.zuct.db.zuct_db.dtos.infos.StudentsInfo;





public class ProgramsBaseDto {
	
	private Long _id;
	
	// Attributes
    private String pr_description;
    private String pr_name;
	
	// Relations lecturers
	private List<Long> _contain_lecturers = new ArrayList<>();
	
	// Relations courses
	private List<Long> _contains_courses = new ArrayList<>();
	
	// Relations students
	private List<Long> _enrolls_students = new ArrayList<>();
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getPr_description() {
		return pr_description;
	}

	public void setPr_description(String pr_description) {
		this.pr_description = pr_description;
	}
	public String getPr_name() {
		return pr_name;
	}

	public void setPr_name(String pr_name) {
		this.pr_name = pr_name;
	}
    
	// Relations lecturers
	
	public List<Long> get_contain_lecturers() {
		return this._contain_lecturers;
	}

    public void set_contain_lecturers(List<LecturersInfo> list) {
		this._contain_lecturers = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	
	// Relations courses
	
	public List<Long> get_contains_courses() {
		return this._contains_courses;
	}

    public void set_contains_courses(List<CoursesInfo> list) {
		this._contains_courses = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	
	// Relations students
	
	public List<Long> get_enrolls_students() {
		return this._enrolls_students;
	}

    public void set_enrolls_students(List<StudentsInfo> list) {
		this._enrolls_students = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	

    
}