package com.zuct.db.zuct_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE StudentsBaseDto PLEASE EDIT ../StudentsDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Students object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.zuct.db.zuct_db.entity.Students;
// Import relations
import com.zuct.db.zuct_db.dtos.infos.ProgramsInfo;




import com.zuct.db.zuct_db.dtos.infos.CoursesInfo;

import com.zuct.db.zuct_db.dtos.infos.LecturersInfo;


public class StudentsBaseDto {
	
	private Long _id;
	
	// Attributes
    private Date date_of_birth;
    private String first_name;
    private String last_name;
    private String middle_name;
    private Double phone;
    private String sex;
	
	// Relations _enrolls
	private Long _enrolls;
	
	
	// Relations m:m _takes
	private List<String> _takes = new ArrayList<>();
	
	// Relations m:m _taught
	private List<String> _taught = new ArrayList<>();
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Date getDate_of_birth() {
		return date_of_birth;
	}

	public void setDate_of_birth(Date date_of_birth) {
		this.date_of_birth = date_of_birth;
	}
	public String getFirst_name() {
		return first_name;
	}

	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}
	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}
	public String getMiddle_name() {
		return middle_name;
	}

	public void setMiddle_name(String middle_name) {
		this.middle_name = middle_name;
	}
	public Double getPhone() {
		return phone;
	}

	public void setPhone(Double phone) {
		this.phone = phone;
	}
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
    
	public void set_enrolls(ProgramsInfo _enrolls) {
		this._enrolls = _enrolls.get_id();
	}

	public Long get_enrolls() {
		return _enrolls;
	}
	

    
	
	public List<String> get_takes() {
		return this._takes;
	}

	public void set_takes(List<CoursesInfo> _takes) {
		_takes.forEach(actor -> {
			this._takes.add(String.valueOf(actor.get_id()));
		});
	}

	
	
	public List<String> get_taught() {
		return this._taught;
	}

	public void set_taught(List<LecturersInfo> _taught) {
		_taught.forEach(actor -> {
			this._taught.add(String.valueOf(actor.get_id()));
		});
	}

	
}