package com.zuct.db.zuct_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CoursesBase PLEASE EDIT ../Courses.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Courses object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.zuct.db.zuct_db.entity.Courses;
// Import relations
import com.zuct.db.zuct_db.entity.Programs;


import com.zuct.db.zuct_db.entity.Lecturers;


import com.zuct.db.zuct_db.entity.Students;




@MappedSuperclass
public class CoursesBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column(nullable=false)
    private String course_code;
	@Column(nullable=false)
    private String course_name;
	
	// Relations _contains
	@ManyToOne(fetch = FetchType.LAZY)
	private Programs _contains;
	
	// Relations _teaches
	@ManyToOne(fetch = FetchType.LAZY)
	private Lecturers _teaches;
	
	@ManyToMany(mappedBy="_takes")
	private List<Students> studentss = new ArrayList<>();
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getCourse_code() {
		return course_code;
	}

	public void setCourse_code(String course_code) {
		this.course_code = course_code;
	}
	public String getCourse_name() {
		return course_name;
	}

	public void setCourse_name(String course_name) {
		this.course_name = course_name;
	}
    
	public void setPrograms(String _contains) {
		this._contains = new Programs(_contains);
	}

	public Programs get_contains() {
		return _contains;
	}
	
	public void setLecturers(String _teaches) {
		this._teaches = new Lecturers(_teaches);
	}

	public Lecturers get_teaches() {
		return _teaches;
	}
	

    
	// Relations students

	public List<Students> getStudents() {
		return this.studentss;
	}

	public void addStudents(Students students) {
		this.studentss.add(students);
	}

	public void removeStudents(Students students) {
		this.studentss.remove(students);
	}
	
}